-- Seed news sources (rss + scraper)

INSERT INTO sources
    (name, method, url, rss_url, credibility, languages, region, source_type, description, category, language, trust_score, priority, enabled, fetch_interval_minutes)
VALUES
('وكالة الأنباء الجزائرية (APS)', 'scraper', 'https://www.aps.dz/', NULL, 'official', 'ar/fr/en', 'algeria', 'official', 'الوكالة الرسمية للدولة الجزائرية', 'general', 'ar', 0.8, 8, TRUE, 30),
('رئاسة الجمهورية', 'scraper', 'https://www.el-mouradia.dz', NULL, 'official', 'ar/fr', 'algeria', 'official', 'الموقع الرسمي للرئاسة', 'general', 'ar', 0.8, 8, TRUE, 30),
('الوزير الأول', 'scraper', 'https://www.premier-ministre.gov.dz', NULL, 'official', 'ar/fr', 'algeria', 'official', NULL, 'general', 'ar', 0.7, 7, TRUE, 30),
('وزارة الدفاع الوطني', 'scraper', 'http://www.mdn.dz', NULL, 'official', 'ar/fr', 'algeria', 'official', NULL, 'general', 'ar', 0.7, 7, TRUE, 30),
('وزارة الشؤون الخارجية', 'scraper', 'https://www.mre.gov.dz', NULL, 'official', 'ar/fr/en', 'algeria', 'official', NULL, 'general', 'ar', 0.7, 7, TRUE, 30),
('وزارة الداخلية', 'scraper', 'https://www.interieur.gov.dz', NULL, 'official', 'ar/fr', 'algeria', 'official', NULL, 'general', 'ar', 0.7, 7, TRUE, 30),
('الشروق أونلاين', 'scraper', 'https://www.echoroukonline.com/', NULL, 'high', 'ar', 'algeria', 'media', 'البوابة الإخبارية للشروق', 'general', 'ar', 0.7, 7, TRUE, 30),
('الخبر', 'scraper', 'https://www.elkhabar.com/', NULL, 'high', 'ar', 'algeria', 'media', 'يومية إخبارية وطنية', 'general', 'ar', 0.7, 7, TRUE, 30),
('النهار أونلاين', 'scraper', 'https://www.ennaharonline.com/', NULL, 'high', 'ar', 'algeria', 'media', 'موقع إخباري خاص', 'general', 'ar', 0.7, 7, TRUE, 30),
('البلاد نت', 'rss', 'https://www.elbilad.net/', 'https://www.elbilad.net/rss', 'high', 'ar', 'algeria', 'media', 'موقع إخباري وطني', 'general', 'ar', 0.7, 7, TRUE, 30),
('TSA الجزائر', 'rss', 'https://www.tsa-algerie.com/', 'https://www.tsa-algerie.com/feed/', 'high', 'fr', 'algeria', 'media', 'أخبار وطنية بالفرنسية', 'general', 'fr', 0.7, 7, TRUE, 30),
('El Watan', 'rss', 'https://elwatan.dz/', 'https://feeds.feedburner.com/elwatan/4pwdGeU2mTa', 'high', 'fr', 'algeria', 'media', 'يومية جزائرية بالفرنسية', 'general', 'fr', 0.7, 7, TRUE, 30),
('Algérie 360', 'rss', 'https://www.algerie360.com/', 'https://www.algerie360.com/feed/', 'medium', 'fr', 'algeria', 'media', NULL, 'general', 'fr', 0.6, 6, TRUE, 30),
('Express DZ', 'rss', 'https://www.expressdz.dz/', 'https://www.expressdz.dz/feed/', 'medium', 'fr', 'algeria', 'media', NULL, 'general', 'fr', 0.6, 6, TRUE, 30),
('Le Matin d''Algérie', 'rss', 'https://lematindalgerie.com/', 'https://lematindalgerie.com/feed/', 'medium', 'fr', 'algeria', 'media', NULL, 'general', 'fr', 0.6, 6, TRUE, 30),
('Observ''Algérie', 'rss', 'https://observalgerie.com/', 'https://observalgerie.com/feed/', 'medium', 'fr', 'algeria', 'media', NULL, 'general', 'fr', 0.6, 6, TRUE, 30),
('الجزيرة نت', 'rss', 'https://www.aljazeera.net/', 'https://www.aljazeera.net/xml/rss/all.xml', 'high', 'ar', 'arab', 'agency', 'قناة الجزيرة الإخبارية', 'general', 'ar', 0.7, 7, TRUE, 30),
('العربية نت', 'rss', 'https://www.alarabiya.net/', 'https://www.alarabiya.net/mrss', 'high', 'ar', 'arab', 'agency', 'قناة العربية الإخبارية', 'general', 'ar', 0.7, 7, TRUE, 30),
('سكاي نيوز عربية', 'rss', 'https://www.skynewsarabia.com/', 'https://www.skynewsarabia.com/rss.xml', 'high', 'ar', 'arab', 'agency', 'قناة سكاي نيوز العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('CNN بالعربية', 'rss', 'https://arabic.cnn.com/', 'https://arabic.cnn.com/api/v1/rss/rss.xml', 'high', 'ar', 'arab', 'agency', 'CNN النسخة العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('BBC عربي', 'rss', 'https://www.bbc.com/arabic', 'https://feeds.bbci.co.uk/arabic/rss.xml', 'high', 'ar', 'arab', 'agency', 'BBC النسخة العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('رويترز عربي', 'scraper', 'https://www.reuters.com/ar/', NULL, 'high', 'ar', 'arab', 'agency', 'وكالة رويترز النسخة العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('فرانس برس عربي', 'scraper', 'https://www.afp.com/ar', NULL, 'high', 'ar', 'arab', 'agency', 'وكالة فرانس برس العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('وكالة الأنباء السعودية (واس)', 'rss', 'https://www.spa.gov.sa/', 'https://www.spa.gov.sa/rss.xml', 'official', 'ar', 'arab', 'agency', 'الوكالة الرسمية السعودية', 'general', 'ar', 0.8, 8, TRUE, 30),
('وكالة أنباء الإمارات (وام)', 'rss', 'https://www.wam.ae/', 'https://www.wam.ae/ar/rss', 'official', 'ar', 'arab', 'agency', 'الوكالة الرسمية الإماراتية', 'general', 'ar', 0.8, 8, TRUE, 30),
('وكالة الأنباء القطرية (قنا)', 'scraper', 'https://www.qna.org.qa/', NULL, 'official', 'ar', 'arab', 'agency', 'الوكالة الرسمية القطرية', 'general', 'ar', 0.8, 8, TRUE, 30),
('وكالة الأناضول', 'scraper', 'https://www.aa.com.tr/ar', NULL, 'high', 'ar', 'arab', 'agency', 'الوكالة التركية النسخة العربية', 'general', 'ar', 0.7, 7, TRUE, 30),
('CNN', 'rss', 'https://www.cnn.com/', 'http://rss.cnn.com/rss/cnn_topstories.rss', 'high', 'en', 'international', 'news', 'CNN International', 'general', 'en', 0.7, 7, TRUE, 30),
('BBC News', 'rss', 'https://www.bbc.com/news', 'http://feeds.bbci.co.uk/news/rss.xml', 'high', 'en', 'international', 'news', 'BBC World News', 'general', 'en', 0.7, 7, TRUE, 30),
('Reuters', 'rss', 'https://www.reuters.com/', 'https://www.reuters.com/rssfeed/worldnews', 'high', 'en', 'international', 'news', 'Reuters News Agency', 'general', 'en', 0.7, 7, TRUE, 30),
('Associated Press (AP)', 'rss', 'https://apnews.com/', 'https://apnews.com/index.rss', 'high', 'en', 'international', 'news', 'AP News', 'general', 'en', 0.7, 7, TRUE, 30),
('France 24', 'rss', 'https://www.france24.com/', 'https://www.france24.com/fr/rss', 'high', 'fr/en/ar/es', 'international', 'news', 'France 24 International', 'general', 'fr', 0.7, 7, TRUE, 30),
('RFI', 'rss', 'https://www.rfi.fr/', 'https://www.rfi.fr/fr/rss', 'high', 'fr/ar/en', 'international', 'news', 'Radio France Internationale', 'general', 'fr', 0.7, 7, TRUE, 30),
('Le Monde', 'rss', 'https://www.lemonde.fr/', 'https://www.lemonde.fr/rss/une.xml', 'high', 'fr', 'international', 'news', 'Le Monde France', 'general', 'fr', 0.7, 7, TRUE, 30),
('Le Figaro', 'rss', 'https://www.lefigaro.fr/', 'https://www.lefigaro.fr/rss/figaro_actualites.xml', 'high', 'fr', 'international', 'news', 'Le Figaro France', 'general', 'fr', 0.7, 7, TRUE, 30),
('Libération', 'rss', 'https://www.liberation.fr/', 'https://www.liberation.fr/arc/outboundfeeds/rss/', 'high', 'fr', 'international', 'news', 'Libération France', 'general', 'fr', 0.7, 7, TRUE, 30),
('The New York Times', 'rss', 'https://www.nytimes.com/', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'high', 'en', 'international', 'news', 'The New York Times', 'general', 'en', 0.7, 7, TRUE, 30),
('The Guardian', 'rss', 'https://www.theguardian.com/', 'https://www.theguardian.com/world/rss', 'high', 'en', 'international', 'news', 'The Guardian UK', 'general', 'en', 0.7, 7, TRUE, 30),
('Euronews', 'rss', 'https://www.euronews.com/', 'https://www.euronews.com/rss', 'high', 'en/fr/ar', 'international', 'news', 'Euronews Europe', 'general', 'en', 0.7, 7, TRUE, 30),
('Bloomberg', 'rss', 'https://www.bloomberg.com/', 'https://feeds.bloomberg.com/markets/news.rss', 'high', 'en', 'economy', 'business', 'Bloomberg Business', 'economy', 'en', 0.7, 7, TRUE, 30),
('Financial Times', 'rss', 'https://www.ft.com/', 'https://www.ft.com/?format=rss', 'high', 'en', 'economy', 'business', 'Financial Times', 'economy', 'en', 0.7, 7, TRUE, 30),
('The Economist', 'rss', 'https://www.economist.com/', 'https://www.economist.com/rss', 'high', 'en', 'economy', 'business', 'The Economist Magazine', 'economy', 'en', 0.7, 7, TRUE, 30),
('Forbes', 'scraper', 'https://www.forbes.com/', NULL, 'high', 'en', 'economy', 'business', 'Forbes Magazine', 'economy', 'en', 0.7, 7, TRUE, 30),
('World Bank', 'rss', 'https://www.worldbank.org/', 'https://www.worldbank.org/en/news.rss', 'official', 'en/ar/fr', 'economy', 'business', 'World Bank News', 'economy', 'en', 0.8, 8, TRUE, 30),
('IMF', 'rss', 'https://www.imf.org/', 'https://www.imf.org/en/News/RSS', 'official', 'en/ar/fr', 'economy', 'business', 'International Monetary Fund', 'economy', 'en', 0.8, 8, TRUE, 30),
('Reuters Business', 'rss', 'https://www.reuters.com/business/', 'https://www.reuters.com/rssfeed/businessNews', 'high', 'en', 'economy', 'business', 'Reuters Business News', 'economy', 'en', 0.7, 7, TRUE, 30),
('الاتحاد الجزائري لكرة القدم (FAF)', 'scraper', 'http://www.faf.dz/', NULL, 'official', 'ar/fr', 'sports', 'football', 'الاتحاد الجزائري', 'sports', 'ar', 0.8, 8, TRUE, 30),
('الرابطة المحترفة (LFP)', 'scraper', 'http://www.lfp.dz/', NULL, 'official', 'ar/fr', 'sports', 'football', 'الدوري الجزائري', 'sports', 'ar', 0.8, 8, TRUE, 30),
('FIFA', 'scraper', 'https://www.fifa.com/', NULL, 'official', 'en/ar/fr', 'sports', 'football', 'الاتحاد الدولي لكرة القدم', 'sports', 'en', 0.8, 8, TRUE, 30),
('CAF', 'scraper', 'https://www.cafonline.com/', NULL, 'official', 'en/ar/fr', 'sports', 'football', 'الاتحاد الأفريقي', 'sports', 'en', 0.8, 8, TRUE, 30),
('UEFA', 'scraper', 'https://www.uefa.com/', NULL, 'official', 'en/ar/fr', 'sports', 'football', 'الاتحاد الأوروبي', 'sports', 'en', 0.8, 8, TRUE, 30),
('ESPN', 'rss', 'https://www.espn.com/', 'https://www.espn.com/espn/rss/news', 'high', 'en', 'sports', 'sports', 'ESPN Sports', 'sports', 'en', 0.7, 7, TRUE, 30),
('Olympic Games', 'scraper', 'https://www.olympics.com/', NULL, 'official', 'en/ar/fr', 'sports', 'sports', 'International Olympic Committee', 'sports', 'en', 0.8, 8, TRUE, 30),
('TechCrunch', 'rss', 'https://techcrunch.com/', 'https://techcrunch.com/feed/', 'high', 'en', 'technology', 'tech', 'TechCrunch News', 'technology', 'en', 0.7, 7, TRUE, 30),
('Wired', 'rss', 'https://www.wired.com/', 'https://www.wired.com/feed/rss', 'high', 'en', 'technology', 'tech', 'Wired Technology', 'technology', 'en', 0.7, 7, TRUE, 30),
('The Verge', 'rss', 'https://www.theverge.com/', 'https://www.theverge.com/rss/index.xml', 'high', 'en', 'technology', 'tech', 'The Verge Tech News', 'technology', 'en', 0.7, 7, TRUE, 30),
('Ars Technica', 'rss', 'https://arstechnica.com/', 'https://feeds.arstechnica.com/arstechnica/index', 'high', 'en', 'technology', 'tech', 'Ars Technica', 'technology', 'en', 0.7, 7, TRUE, 30),
('CNET', 'rss', 'https://www.cnet.com/', 'https://www.cnet.com/rss/news/', 'high', 'en', 'technology', 'tech', 'CNET Technology', 'technology', 'en', 0.7, 7, TRUE, 30),
('MIT Technology Review', 'rss', 'https://www.technologyreview.com/', 'https://www.technologyreview.com/topnews.rss', 'high', 'en', 'technology', 'tech', 'MIT Tech Review', 'technology', 'en', 0.7, 7, TRUE, 30),
('BBC Technology', 'rss', 'https://www.bbc.com/news/technology', 'http://feeds.bbci.co.uk/news/technology/rss.xml', 'high', 'en', 'technology', 'tech', 'BBC Tech News', 'technology', 'en', 0.7, 7, TRUE, 30),
('World Health Organization', 'rss', 'https://www.who.int/', 'https://www.who.int/rss-feeds', 'official', 'en/ar/fr', 'science', 'health', 'WHO News', 'health', 'en', 0.8, 8, TRUE, 30),
('Nature', 'rss', 'https://www.nature.com/', 'http://feeds.nature.com/nature/rss/current', 'high', 'en', 'science', 'science', 'Nature Scientific Journal', 'science', 'en', 0.7, 7, TRUE, 30),
('Science Daily', 'rss', 'https://www.sciencedaily.com/', 'https://www.sciencedaily.com/rss/all.xml', 'high', 'en', 'science', 'science', 'Science Daily News', 'science', 'en', 0.7, 7, TRUE, 30),
('Science Magazine', 'rss', 'https://www.science.org/', 'https://www.science.org/rss/news_current.xml', 'high', 'en', 'science', 'science', 'AAAS Science Magazine', 'science', 'en', 0.7, 7, TRUE, 30),
('Google News - Algérie', 'rss', 'https://news.google.com/topics/CAAqJQgKIh9DQkFTRVFvSUwyMHZNRFZ4ZW1jU0JXWnlMVVpTS0FBUAE?hl=fr&gl=DZ&ceid=DZ:fr', 'https://news.google.com/rss/search?q=Algérie&hl=fr&gl=FR&ceid=FR:fr', 'high', 'fr', 'algeria', 'aggregator', 'Google News Algérie', 'general', 'fr', 0.7, 7, TRUE, 30),
('Google News - World', 'rss', 'https://news.google.com/', 'https://news.google.com/rss', 'high', 'en', 'international', 'aggregator', 'Google News International', 'general', 'en', 0.7, 7, TRUE, 30),
('BFM TV - Algérie', 'rss', 'https://www.bfmtv.com/international/afrique/algerie/', 'https://www.bfmtv.com/rss/international/afrique/algerie/', 'medium', 'fr', 'algeria', 'media', 'BFM TV Algérie', 'general', 'fr', 0.6, 6, TRUE, 30),
('Courrier International - Algérie', 'rss', 'https://www.courrierinternational.com/tag/algerie', 'https://www.courrierinternational.com/feed/rubrique/algerie/rss.xml', 'medium', 'fr', 'algeria', 'media', 'Courrier International', 'general', 'fr', 0.6, 6, TRUE, 30),
('France Info - Algérie', 'rss', 'https://www.franceinfo.fr/monde/afrique/algerie', 'https://www.franceinfo.fr/monde/afrique/algerie.rss', 'high', 'fr', 'algeria', 'media', 'France Info Algérie', 'general', 'fr', 0.7, 7, TRUE, 30),
('Le Point - Algérie', 'rss', 'https://www.lepoint.fr/tags/algerie', 'https://www.lepoint.fr/arc/outboundfeeds/rss/tags_slug/algerie/', 'medium', 'fr', 'algeria', 'media', 'Le Point Algérie', 'general', 'fr', 0.6, 6, TRUE, 30),
('L''Humanité - Algérie', 'rss', 'https://www.humanite.fr/mot-cle/algerie', 'https://www.humanite.fr/mot-cle/algerie/feed', 'medium', 'fr', 'algeria', 'media', 'L''Humanité Algérie', 'general', 'fr', 0.6, 6, TRUE, 30);
ON CONFLICT (url) DO NOTHING;

UPDATE sources
SET slug = lower(replace(name, ' ', '-'))
WHERE slug IS NULL;
